config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth'}

  resources :posts do
    member do
      put :like, to:'posts#upvote'
      put :dislike, to:'posts#downvote'
    end

    resources :comments do
      resources :answers
      member do
        put :like, to:'comments#upvote'
        put :dislike, to:'comments#downvote'
        patch :choose_best
      end
    end

    delete :destroy_attachment
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, :on => :collection
        get :all, :on => :collection
      end
      resources :posts do
        resources :posts, only: %i[index create]
      end
      resources :posts, only: :show
    end
  end

  root "posts#index"
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :answers
  validates :comment, presence: true
  validates :name, presence: true
  has_one_attached :file
  after_create_commit { RenderCommentJob.perform_later self }
  acts_as_votable

  scope :best_comments,     -> { where(best: true) }
  scope :not_best_comments, -> { where(best: false) }

  def choose_best!
      ActiveRecord::Base.transaction do
          post.comments.update_all(best: false)
          update!(best: true)

      end
    end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController
  before_action :authenticate_user!, only: :create
  before_action :find_post, only: :create

  def show
    respond_with Comment.find(params[:id]), adapter: :json, serializer: CommentSerializer
  end

  def index
    respond_with Comment.where(post_id: params[:post_id]), adapter: :json
  end

  def create
    if can?(:create, Comment)
      @comment = @post.comments.create(comment_params)
      render json: @comment, adapter: :json, serializer: CommentSerializer
    else
      render json: { message: 'Permission denied or not enough permissions.' }, status: :forbidden
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params[:comment].try(:permit, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:destroy, :downvote, :upvote, :choose_best]
  before_action :authenticate_user!, only: [:destroy, :downvote, :upvote]
  after_action :publish_comment, only: [:create]

  def create
    @post = Post.find(params['post_id'])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment, :user_id, :best, :file))
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end

  def publish_comment
    ActionCable.server.broadcast("post_channel_#{@comment.post_id}", {title: @comment.name, content: @comment.comment})
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end

  def choose_best
    @comment.choose_best!
    redirect_to post_path(@post)
  end

  def upvote
    if @comment.voted_up_by? current_user
      @comment.unvote_by(current_user)
    else
      @comment.upvote_by(current_user)
    end
    redirect_back fallback_location: root_path
  end

  def downvote
    if @comment.voted_down_by? current_user
      @comment.unvote_by(current_user)
    else
      @comment.downvote_by(current_user)
    end
    redirect_back fallback_location: root_path
  end

  def destroy_attachment
    @file = ActiveStorage::Attachment.find_by(params[:id])
    @file.purge
    redirect_back(fallback_location: posts_path)
  end

  private

  def find_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="post-id" data-post-id="<%= @post_id %>"> </div>
<div id="comment_<%= comment.id %>">
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <div class="content">
          <strong>
            <%= comment.name %>
          </strong>
          </div>
        <% @comment = comment %>
          <%= @comment.comment %>
        <% if @comment.best? %>
          <h1>лучший</h1>
          <% else %>
          <h1>не лучший</h1>
          <% end %>
        <%=link_to 'Best', choose_best_post_comment_path(comment.post, comment), method: :patch, remote: true,
                   class: 'best-answer-btn btn btn-success', id: "best-comment-link-#{comment.id}"%>
        <br>
        <h>Comments:</h>
        <br>
        <%= render @comment.answers %>
        <%= render 'answers/form' %>
          <br>
            <br>
        <div id="voting">
            <%= link_to like_post_comment_path(comment.post, comment), method: :put do %>
          <%= image_tag "1200px-Green_Arrow_Up.svg.png" %>
          <% end %>
          <div class="vot">
            <%= comment.get_upvotes.size-comment.get_downvotes.size %>
          </div>
          <div class="downbutton">
            <%= link_to dislike_post_comment_path(comment.post, comment), method: :put do %>
              <%= image_tag "1200px-Red_Arrow_Down.svg.png" %>
              <% end %>
          </div>
        </div>
        </p>
        <div class="file">
          <% if comment.file.attached? %>
            <%= link_to 'Download attached file', comment.file %>
<!--            Пофиксить-->
<!--            <div class="remove-file">-->
              <%#= link_to 'Remove', post_comment_destroy_attachment_path(comment.post, comment.file.first), method: :delete, data: { confirm: 'Are you sure?' } %>
<!--            </div>-->
          <% else %>
            <% nil %>
          <% end %>
        </div>
      </div>
    </div>
    <% if can?(:destroy, Comment) %>
      <%= link_to 'Delete', [comment.post, comment], remote: true, method: :delete, class: "button is-danger",
                  data: { confirm: 'Are you sure that you want to delete this answer?' }%>
      <% end %>
  </article>
</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build], remote: true) do |f| %>
  <div class="field">
    <div class="control">
<!--      <h1 hidden><%#= (f.text_field :best, value: false ).freeze %></h1>-->
<!--      <h1 hidden><%#= (f.text_field :user_id, value: "#{current_user.id}").freeze %></h1>-->
      <%= f.input :name, input_html: { class: 'input' }, remote: true, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :comment, input_html: { class: 'textarea' }, remote: true, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <%= f.button :submit, class: "button is-primary"%>
<% end %>

app/views/comments/choose_best.js.erb
<%# if @comment.best? %>
<%# end %>
<% if @comment.best? %>
$('.comments').html('<%= j render 'posts/form', post: @post.comment %>');
$('.comment-form').on('click', function (e) {
    e.preventDefault();
    $(this).hide();
    var comment_id = $(this).parents('.comment').data('commentID');
    $('#best-comment-link-' + comment_id).hide();
})
<% end %>

app/views/comments/create.js.erb
function eraseText() {
    document.getElementById("comment_comment").value = "";
    document.getElementById("comment_name").value = "";
}
$('#comment_content').append('<%= j render(@comment) %>');
eraseText()

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();