config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth'}

  resources :posts do
    member do
      put :like, to:'posts#upvote'
      put :dislike, to:'posts#downvote'
    end

    resources :comments do
      resources :answers
      member do
        put :like, to:'comments#upvote'
        put :dislike, to:'comments#downvote'
        patch :choose_best
      end
    end

    delete :destroy_attachment
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, :on => :collection
        get :all, :on => :collection
      end
      resources :posts do
        resources :posts, only: %i[index create]
      end
      resources :posts, only: :show
    end
  end

  root "posts#index"
  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  has_many_attached :file
  has_many :comments
  # has_many :subscriptions, dependent: :delete_all
  belongs_to :user, class_name: "User", optional: true
  acts_as_votable
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  def index
    @posts = Post.all
    respond_with @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :edit, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, only: [:update, :edit, :destroy]
  after_action :publish_post, only: [:create]

  respond_to :html, :json

  authorize_resource

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result
    # respond_with(@posts = Post.all.order("created_at DESC"))
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def create
    respond_with(@post = Post.create(post_params))
    @post[:user_id] = current_user.id
  end

  def publish_post
    ActionCable.server.broadcast "posts_channel", {title: @post.title, content: @post.content, id: @post.id}
  end

  def show
    @post_id = @post[:id]
    respond_with @post
  end

  def update
    @post.update(post_params)
    respond_with @post
  end

  def edit
  end

  def destroy
    respond_with(@post.destroy)
  end

  def upvote
    if @post.voted_up_by? current_user
      @post.unvote_by(current_user)
    else
      @post.upvote_by(current_user)
    end
    redirect_back fallback_location: root_path
  end

  def downvote
    if @post.voted_down_by? current_user
      @post.unvote_by(current_user)
    else
      @post.downvote_by(current_user)
    end
    redirect_back fallback_location: root_path
  end

  def destroy_attachment
    @file = ActiveStorage::Attachment.find_by(params[:id])
    @file.purge
    redirect_back(fallback_location: posts_path)
  end

  private

  def flash_interpolation_options
    { resource_name: 'New awesome post', time: @post.created_at, user: current_user.email}
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :file).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_form.html.erb
<div class="section">
  <%= simple_form_for @post, remote: true do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <div class="field">
      <%= f.label :file %>
      <%= f.file_field :file %>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-primary"%>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>
<div id="post-id" data-post-id="<%= @post.try(:id) %>"></div>

<section>
<div class="container">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4" id="post_title"></p>
          </div>
        </div>
        <div class="content" id=post_content>
        </div>
      </div>
    </div>
</div>

  <div class="container">
    <%= search_form_for @q do |f| %>
      <%= f.search_field :title_or_content_cont %>
      <%= f.submit %>
      <% end %>
    <% @posts.each do |post| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4"> <%= link_to post.title, post %></p>
          </div>
        </div>
        <div class="content">
          <%= post.content %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new question" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>
<div id="post-id" data-post-id="<%= @post_id %>">

</div>
<section class="section">
  <div class="container">
    <h1 class="title">
      <%= @post.title %>
    </h1>
    <nav class="level">
      <div class="level-left">
        <p class="level-item">
          <strong>Actions</strong>
        </p>
      </div>

      <div class="level-right">
        <p class="level-item">
          <% if can?(:edit, Post) %>
          <%= link_to "Edit", edit_post_path(@post), class: "button" %>
            <% end %>
        </p>
        <p class="level-item">
          <% if can?(:destroy, Post) %>
            <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure that you want to delete this question?" },
                        class: "button is-danger"%>
          <% end %>
        </p>
      </div>

    </nav>
    <hr />

    <div class="content">
      <%= @post.content %>
    </div>

    <div class="attachment-gallery">
    </div>
    <div class="file">
      <p>
          <%= @post.get_upvotes.size-@post.get_downvotes.size %>
          <%= link_to "Like", like_post_path(@post.id), method: :put, class: "button"%>
          <%= link_to "Dislike", dislike_post_path(@post), method: :put, class: "button"%>
      </p>
      <% if @post.file.attached? %>
        <%= link_to 'Download attached file', @post.file.first %>
        <% if current_user.id == @post[:user_id] %>
        <div class="delete-button">
          <%= link_to 'Remove', post_destroy_attachment_path(@post.file),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        <% else %>
      <% nil %>
          <% end %>
        </div>
      <% else %>
        <% nil %>
      <% end %>
    </div>

  </div>

</section>

<section class="section comments" id="post_comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong>
      <%= @post.comments.count %>
    </strong> Comments </h2>
    <div class="content">
<!--      Пофиксить ActionCable комментов (сделать всё покрасивше)-->
      <div id="named_comment">
      </div>
      <div id="comment_content">
      </div>
      <div id="comment_answers">
      </div>
    </div>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-3">
        Leave a reply
      </h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>